// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewGist(arg1, arg2) {
  return window['go']['main']['App']['CreateNewGist'](arg1, arg2);
}

export function GetGistContent(arg1, arg2) {
  return window['go']['main']['App']['GetGistContent'](arg1, arg2);
}

export function GetGistsForAuthenticatedUser(arg1) {
  return window['go']['main']['App']['GetGistsForAuthenticatedUser'](arg1);
}

export function GetMoreInformationFromURL(arg1, arg2) {
  return window['go']['main']['App']['GetMoreInformationFromURL'](arg1, arg2);
}

export function GetPublicGists() {
  return window['go']['main']['App']['GetPublicGists']();
}

export function GetPublicRepositories() {
  return window['go']['main']['App']['GetPublicRepositories']();
}

export function GetRepositoriesForAuthenticatedUser(arg1) {
  return window['go']['main']['App']['GetRepositoriesForAuthenticatedUser'](arg1);
}
