// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNewGist(arg1:main.Gist,arg2:string):Promise<any>;

export function GetGistContent(arg1:string,arg2:string):Promise<string>;

export function GetGistsForAuthenticatedUser(arg1:string):Promise<main.APIResponse>;

export function GetMoreInformationFromURL(arg1:string,arg2:string):Promise<main.APIResponse>;

export function GetPublicGists():Promise<main.APIResponse>;

export function GetPublicRepositories():Promise<main.APIResponse>;

export function GetRepositoriesForAuthenticatedUser(arg1:string):Promise<main.APIResponse>;
